const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Acts.SetWarnOnClose,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Acts.MoveToTop
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{tile_ground: 0},
	{tile_soil: 0},
	{herohealth: 0},
	{canbehit: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{hero: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{bullet: 0},
	{State: 0},
	{enemylvl1health: 0},
	{Fade: 0},
	{enemylvl1: 0},
	{Pin: 0},
	{Sprite: 0},
	{coin: 0},
	{Cointxt: 0},
	{box: 0},
	{attacktext: 0},
	{levelcomplete1door: 0},
	{levelcomplete1wall: 0},
	{Sine: 0},
	{box_moving_lvl2: 0},
	{enemyhealth2: 0},
	{enemylvl2: 0},
	{Sprite2: 0},
	{levelcomplete2wall: 0},
	{levelcomplete2door: 0},
	{box_moving_lvl3: 0},
	{levelcomplete3wall: 0},
	{levelcomplete3door: 0},
	{enemylvl3: 0},
	{Sprite3: 0},
	{bonuslvldoor: 0},
	{bonuslvl_tile_ground: 0},
	{bonuslvl_tile_soil: 0},
	{bonuslvl_finished: 0},
	{spawn_after_bonuslvl: 0},
	{bonus_lvl_txt: 0},
	{background: 0},
	{background_sky2: 0},
	{bush: 0},
	{Sprite4: 0},
	{rock: 0},
	{bush2: 0},
	{deadtree: 0},
	{tools: 0},
	{axe: 0},
	{smallrock: 0},
	{background2: 0},
	{background3: 0},
	{background4: 0},
	{background5: 0},
	{background6: 0},
	{background7: 0},
	{wall: 0},
	{window: 0},
	{door: 0},
	{roofleft: 0},
	{roofright: 0},
	{dirt: 0},
	{fence: 0},
	{stonefloor: 0},
	{door4: 0},
	{doortest: 0},
	{levelcomplete4door: 0},
	{levelcomplete2door5: 0},
	{square: 0},
	{restart: 0},
	{Touch: 0},
	{pause: 0},
	{pauselayer: 0},
	{resume: 0},
	{lvl4end: 0},
	{coin2: 0},
	{levelcomplete3door2: 0},
	{hero_shadow: 0},
	{resume_button: 0},
	{mainmenu_background: 0},
	{play_button: 0},
	{mainmenu_button_play: 0},
	{button_panel: 0},
	{mainmenu_button_quit: 0},
	{quit_button: 0},
	{Browser: 0},
	{levels_back_panel: 0},
	{levels_small_panel: 0},
	{levels_back_to_menu_button: 0},
	{lvl1: 0},
	{lvl2: 0},
	{lvl3: 0},
	{lvl4: 0},
	{lvl5: 0},
	{lvl6: 0},
	{lvl7: 0},
	{lvl8: 0},
	{lvl9: 0},
	{menu_button: 0},
	{menu: 0},
	{blocker_1: 0},
	{enable_blocker: 0},
	{lives: 0},
	{coinHUD: 0},
	{background_lvl8: 0},
	{button_panel2: 0},
	{mainmenu_button_credits: 0},
	{credits_back_panel2: 0},
	{credits_back_to_menu_button2: 0},
	{Credits_text: 0},
	{Credits_title: 0},
	{deadtree2: 0},
	{deadtree3: 0},
	{deadtree4: 0},
	{deadtree5: 0},
	{deadtree6: 0},
	{ruin: 0},
	{ruin2: 0},
	{ruin3: 0},
	{ruin5: 0},
	{ruins6: 0},
	{waste1: 0},
	{Audio: 0},
	{Background_ForestFate_past: 0},
	{Background_ForestFate_future: 0},
	{beginning_text: 0},
	{Play_btn: 0},
	{beginning_text2: 0},
	{Play_btn2: 0},
	{Background_UrbanEvolution_past: 0},
	{beginning_text3: 0},
	{Play_btn3: 0},
	{Background_ForestFate_past2: 0},
	{beginning_text4: 0},
	{Play_btn4: 0},
	{beginning_text5: 0},
	{Play_btn5: 0},
	{Background_RiversJourney_Present: 0},
	{Background_RiversJourney_past: 0},
	{beginning_text6: 0},
	{Play_btn6: 0},
	{Background_UrbanEvolution_present: 0},
	{Background_UrbanEvolution_future: 0},
	{background1: 0},
	{background22: 0},
	{backrground33: 0},
	{background444: 0},
	{background2255: 0},
	{background88: 0},
	{herolives: 0},
	{coinscore: 0},
	{herolives2: 0},
	{coinscore2: 0},
	{herolives3: 0},
	{coinscore3: 0},
	{bonuslvl: 0},
	{herolives4: 0},
	{coinscore4: 0},
	{herolives5: 0},
	{coinscore5: 0},
	{herolives6: 0},
	{coinscore6: 0},
	{bonuslvl2: 0},
	{herolives7: 0},
	{coinscore7: 0},
	{bonuslvl3: 0},
	{herolives8: 0},
	{coinscore8: 0},
	{bonuslvl4: 0},
	{FullText: 0},
	{CharIndex: 0}
];

self.InstanceType = {
	tile_ground: class extends self.ISpriteInstance {},
	tile_soil: class extends self.ISpriteInstance {},
	hero: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	herohealth: class extends self.ITextInstance {},
	bullet: class extends self.ISpriteInstance {},
	enemylvl1: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	Cointxt: class extends self.ITextInstance {},
	box: class extends self.ISpriteInstance {},
	attacktext: class extends self.ITextInstance {},
	levelcomplete1door: class extends self.ISpriteInstance {},
	levelcomplete1wall: class extends self.ISpriteInstance {},
	box_moving_lvl2: class extends self.ISpriteInstance {},
	enemylvl2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	levelcomplete2wall: class extends self.ISpriteInstance {},
	levelcomplete2door: class extends self.ISpriteInstance {},
	box_moving_lvl3: class extends self.ISpriteInstance {},
	levelcomplete3wall: class extends self.ISpriteInstance {},
	levelcomplete3door: class extends self.ISpriteInstance {},
	enemylvl3: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	bonuslvldoor: class extends self.ISpriteInstance {},
	bonuslvl_tile_ground: class extends self.ISpriteInstance {},
	bonuslvl_tile_soil: class extends self.ISpriteInstance {},
	bonuslvl_finished: class extends self.ISpriteInstance {},
	spawn_after_bonuslvl: class extends self.ISpriteInstance {},
	bonus_lvl_txt: class extends self.ITextInstance {},
	background: class extends self.ISpriteInstance {},
	background_sky2: class extends self.ISpriteInstance {},
	bush: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	bush2: class extends self.ISpriteInstance {},
	deadtree: class extends self.ISpriteInstance {},
	tools: class extends self.ISpriteInstance {},
	axe: class extends self.ISpriteInstance {},
	smallrock: class extends self.ISpriteInstance {},
	background2: class extends self.ISpriteInstance {},
	background3: class extends self.ISpriteInstance {},
	background4: class extends self.ISpriteInstance {},
	background5: class extends self.ISpriteInstance {},
	background6: class extends self.ISpriteInstance {},
	background7: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	window: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	roofleft: class extends self.ISpriteInstance {},
	roofright: class extends self.ISpriteInstance {},
	dirt: class extends self.ISpriteInstance {},
	fence: class extends self.ISpriteInstance {},
	stonefloor: class extends self.ISpriteInstance {},
	door4: class extends self.ISpriteInstance {},
	doortest: class extends self.ISpriteInstance {},
	levelcomplete4door: class extends self.ISpriteInstance {},
	levelcomplete2door5: class extends self.ISpriteInstance {},
	square: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	pause: class extends self.ISpriteInstance {},
	pauselayer: class extends self.ISpriteInstance {},
	resume: class extends self.ISpriteInstance {},
	lvl4end: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	levelcomplete3door2: class extends self.ISpriteInstance {},
	hero_shadow: class extends self.ISpriteInstance {},
	resume_button: class extends self.ITextInstance {},
	mainmenu_background: class extends self.ISpriteInstance {},
	play_button: class extends self.ISpriteInstance {},
	mainmenu_button_play: class extends self.ITextInstance {},
	button_panel: class extends self.ISpriteInstance {},
	mainmenu_button_quit: class extends self.ITextInstance {},
	quit_button: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	levels_back_panel: class extends self.ISpriteInstance {},
	levels_small_panel: class extends self.ISpriteInstance {},
	levels_back_to_menu_button: class extends self.ISpriteInstance {},
	lvl1: class extends self.ITextInstance {},
	lvl2: class extends self.ITextInstance {},
	lvl3: class extends self.ITextInstance {},
	lvl4: class extends self.ITextInstance {},
	lvl5: class extends self.ITextInstance {},
	lvl6: class extends self.ITextInstance {},
	lvl7: class extends self.ITextInstance {},
	lvl8: class extends self.ITextInstance {},
	lvl9: class extends self.ITextInstance {},
	menu_button: class extends self.ITextInstance {},
	menu: class extends self.ISpriteInstance {},
	blocker_1: class extends self.ISpriteInstance {},
	enable_blocker: class extends self.ISpriteInstance {},
	lives: class extends self.ISpriteInstance {},
	coinHUD: class extends self.ISpriteInstance {},
	background_lvl8: class extends self.ISpriteInstance {},
	button_panel2: class extends self.ISpriteInstance {},
	mainmenu_button_credits: class extends self.ITextInstance {},
	credits_back_panel2: class extends self.ISpriteInstance {},
	credits_back_to_menu_button2: class extends self.ISpriteInstance {},
	Credits_text: class extends self.ITextInstance {},
	Credits_title: class extends self.ITextInstance {},
	deadtree2: class extends self.ISpriteInstance {},
	deadtree3: class extends self.ISpriteInstance {},
	deadtree4: class extends self.ISpriteInstance {},
	deadtree5: class extends self.ISpriteInstance {},
	deadtree6: class extends self.ISpriteInstance {},
	ruin: class extends self.ISpriteInstance {},
	ruin2: class extends self.ISpriteInstance {},
	ruin3: class extends self.ISpriteInstance {},
	ruin5: class extends self.ISpriteInstance {},
	ruins6: class extends self.ISpriteInstance {},
	waste1: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Background_ForestFate_past: class extends self.ISpriteInstance {},
	Background_ForestFate_future: class extends self.ISpriteInstance {},
	beginning_text: class extends self.ITextInstance {},
	Play_btn: class extends self.ISpriteInstance {},
	beginning_text2: class extends self.ITextInstance {},
	Play_btn2: class extends self.ISpriteInstance {},
	Background_UrbanEvolution_past: class extends self.ISpriteInstance {},
	beginning_text3: class extends self.ITextInstance {},
	Play_btn3: class extends self.ISpriteInstance {},
	Background_ForestFate_past2: class extends self.ISpriteInstance {},
	beginning_text4: class extends self.ITextInstance {},
	Play_btn4: class extends self.ISpriteInstance {},
	beginning_text5: class extends self.ITextInstance {},
	Play_btn5: class extends self.ISpriteInstance {},
	Background_RiversJourney_Present: class extends self.ISpriteInstance {},
	Background_RiversJourney_past: class extends self.ISpriteInstance {},
	beginning_text6: class extends self.ITextInstance {},
	Play_btn6: class extends self.ISpriteInstance {},
	Background_UrbanEvolution_present: class extends self.ISpriteInstance {},
	Background_UrbanEvolution_future: class extends self.ISpriteInstance {},
	background1: class extends self.ISpriteInstance {},
	background22: class extends self.ISpriteInstance {},
	backrground33: class extends self.ISpriteInstance {},
	background444: class extends self.ISpriteInstance {},
	background2255: class extends self.ISpriteInstance {},
	background88: class extends self.ISpriteInstance {}
}